### ISSUE TITLE
Cerbero recipe 'gettext' failed at the build step 'configure'

### ISSUE THREAD

**Issue by phetroy** [nirbheek/cerbero#1]
Hi there, 

Here are the following steps that ended up in a build failure:

1. I was going through the different steps on the following documentation here:
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero

2. I was able to get to the android following command:
./cerbero-uninstalled -c config/cross-android-armv7.cbc package openwebrtc

3. The build stops as I'm getting the following error:
checking for arm-linux-androideabi-gcc... arm-linux-androideabi-gcc -fuse-ld=gold
**checking whether the C compiler works... no**
configure: error: in `/Users/patrick.hetroy/cerbero/sources/android_armv7/gettext-0.18.3.2/gettext-runtime':
configure: error: C compiler cannot create executables
See `config.log' for more details
Running command './configure --prefix /Users/patrick.hetroy/cerbero/dist/android_armv7 --libdir /Users/patrick.hetroy/cerbero/dist/android_armv7/lib  --disable-maintainer-mode  --disable-silent-rules  --disable-introspection  --host=arm-linux-androideabi'

**Recipe 'gettext' failed at the build step 'configure'**

Do you know why the C compiler breaks this with the latest code?

Thanks a lot!

**Comment by nirbheek** [comment]
The instructions on the wiki page aren't clear on this; sorry about that. You need to bootstrap each config (-c param) before building something with it. So before you do 

./cerbero-uninstalled -c config/cross-android-armv7.cbc package openwebrtc

You need to prepare that config by running:

./cerbero-uninstalled -c config/cross-android-armv7.cbc bootstrap

Please note that this only needs to be done the first time you build something with that config.

**Comment by phetroy** [comment]
Cool, thanks I updated the doc as well :)

**Comment by stefanalund** [comment]
@phetroy big thanks!
