### ISSUE TITLE
glib build failed

### ISSUE THREAD

**Issue by KerwinMa** [nirbheek/cerbero#14]
Trying to build it with cerebro on a mac 10.9, got a failure message:
/bin/sh ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I..  -I.. -I../glib -I../glib -I..  -DG_LOG_DOMAIN=\"GLib\" -DG_DISABLE_CAST_CHECKS -DGLIB_COMPILATION -DPCRE_STATIC -xobjective-c -D_REENTRANT -Wall -Wstrict-prototypes -Werror=declaration-after-statement -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=pointer-arith -Werror=init-self -Werror=format-security -Werror=format=2 -Werror=missing-include-dirs -fvisibility=hidden -Wall -g -O2 -arch x86_64 -m64 -Wno-error=format-nonliteral  -I/Users/kerwinma/cerbero/build-tools/include -mmacosx-version-min=10.8 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk  -Wall -g -O2 -arch x86_64 -m64 -Wno-error=format-nonliteral  -I/Users/kerwinma/cerbero/build-tools/include -mmacosx-version-min=10.8 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk  -DHAVE_STRNDUP  -MT libglib_2_0_la-gmain.lo -MD -MP -MF .deps/libglib_2_0_la-gmain.Tpo -c -o libglib_2_0_la-gmain.lo `test -f 'gmain.c' || echo './'`gmain.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I.. -I../glib -I../glib -I.. -DG_LOG_DOMAIN=\"GLib\" -DG_DISABLE_CAST_CHECKS -DGLIB_COMPILATION -DPCRE_STATIC -xobjective-c -D_REENTRANT -Wall -Wstrict-prototypes -Werror=declaration-after-statement -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=pointer-arith -Werror=init-self -Werror=format-security -Werror=format=2 -Werror=missing-include-dirs -fvisibility=hidden -Wall -g -O2 -arch x86_64 -m64 -Wno-error=format-nonliteral -I/Users/kerwinma/cerbero/build-tools/include -mmacosx-version-min=10.8 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -Wall -g -O2 -arch x86_64 -m64 -Wno-error=format-nonliteral -I/Users/kerwinma/cerbero/build-tools/include -mmacosx-version-min=10.8 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -DHAVE_STRNDUP -MT libglib_2_0_la-gmain.lo -MD -MP -MF .deps/libglib_2_0_la-gmain.Tpo -c gmain.c  -fno-common -DPIC -o .libs/libglib_2_0_la-gmain.o
gmain.c:5980:40: error: use of undeclared identifier 'NSEventSubtype'; did you mean 'NSEventType'?
                              subtype: GMAIN_COCOA_EVENT_SUBTYPE_EVENTLOOP
                                       ^
gmain.c:507:47: note: expanded from macro 'GMAIN_COCOA_EVENT_SUBTYPE_EVENTLOOP'
#define GMAIN_COCOA_EVENT_SUBTYPE_EVENTLOOP ((NSEventSubtype)31722)
                                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:56:20: note: 'NSEventType' declared here
typedef NSUInteger NSEventType;
                   ^
gmain.c:6316:26: error: use of undeclared identifier 'NSEventSubtype'; did you mean 'NSEventType'?
      [event subtype] == GMAIN_COCOA_EVENT_SUBTYPE_EVENTLOOP)
                         ^
gmain.c:507:47: note: expanded from macro 'GMAIN_COCOA_EVENT_SUBTYPE_EVENTLOOP'
#define GMAIN_COCOA_EVENT_SUBTYPE_EVENTLOOP ((NSEventSubtype)31722)
                                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:56:20: note: 'NSEventType' declared here
typedef NSUInteger NSEventType;
                   ^
2 errors generated.
make[4]: *** [libglib_2_0_la-gmain.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Running command 'make'

Recipe 'glib' failed at the build step 'compile'
Select an action to proceed:

**Comment by sdroege** [comment]
NSEventSubtype seems to be new in 10.10

**Comment by KerwinMa** [comment]
Thanks. It is. I will update my system.

**Comment by sdroege** [comment]
This is fixed here now: http://cgit.freedesktop.org/gstreamer/cerbero/commit/?id=3621637171eb720853d83b5131bac7044ce6836e

Should be in the openwebrtc cerbero soonish.
