### ISSUE TITLE
 error: no dependency information found for /home/kerwin/cerbero/dist/linux_x86_64/lib/libusrsctp.so.1

### ISSUE THREAD

**Issue by KerwinMa** [nirbheek/cerbero#15]
I got the error on ubuntu server 14.10 64bit when build openwebrtc cerbero.
~/cerbero$ ./cerbero-uninstalled package openwebrtc
dpkg-shlibdeps: error: no dependency information found for /home/kerwin/cerbero/dist/linux_x86_64/lib/libusrsctp.so.1 (used by debian/openwebrtc-base/home/kerwin/cerbero/dist/linux_x86_64/lib/gstreamer-1.0/libgstsctp.so)

**Comment by nirbheek** [comment]
All development has moved to https://github.com/EricssonResearch/cerbero
