### ISSUE TITLE
ICU sometimes fails to build with "fatal error: typeinfo: No such file or directory"

### ISSUE THREAD

**Issue by KerwinMa** [nirbheek/cerbero#17]
Trying to build it for Android on ubuntu 14.04 server, get the following error. I tried to find the 'typeinfo' file as specified '-I/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm/usr/include', no such file. Is it the known issue? Seems there is someone has successfully complied OpenwebRTC for android.

make[1]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/icu/source/common'
   arm-linux-androideabi-g++	 ...  ustrenum.cpp
In file included from ustrenum.cpp:11:0:
utypeinfo.h:28:45: fatal error: typeinfo: No such file or directory
 #include <typeinfo>  // for 'typeid' to work
                                             ^
compilation terminated.
*** Failed compilation command follows: ----------------------------------------------------------
arm-linux-androideabi-g++ -fuse-ld=gold --sysroot=/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm -I/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm/usr/include -DANDROID -DPIC -D__ARM_ARCH_7A__ -D_REENTRANT -DU_HAVE_ELF_H=1 -DU_HAVE_STD_STRING=0 -DU_HAVE_ATOMIC=0 -DU_DISABLE_RENAMING=1 -I. -DDEFAULT_ICU_PLUGINS="/home/kerwin/cerbero/dist/android_armv7/lib/icu"  -DU_ATTRIBUTE_DEPRECATED= -DU_COMMON_IMPLEMENTATION -Wall -g -Os --sysroot=/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm -I/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm/usr/include -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -fPIC -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -DANDROID -DPIC -D__ARM_ARCH_7A__ -Wa,--noexecstack -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long --std=c++0x -c -o ustrenum.ao ustrenum.cpp
--- ( rebuild with "make VERBOSE=1 all" to show all parameters ) --------
make[1]: *** [ustrenum.ao] Error 1
make[1]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/icu/source/common'
make: *** [all-recursive] Error 2
Running command 'make'

**Comment by KerwinMa** [comment]
The 'typeinfo' files are sitting in the following folders:
kerwin@ubuntu:~/cerbero$ cd $NDK_ROOT
kerwin@ubuntu:~/cerbero/android-ndk-r10d$ find ./ -name 'typeinfo'
./sources/cxx-stl/gnu-libstdc++/4.6/include/typeinfo
./sources/cxx-stl/gnu-libstdc++/4.9/include/typeinfo
./sources/cxx-stl/gnu-libstdc++/4.8/include/typeinfo
./sources/cxx-stl/llvm-libc++/libcxx/include/typeinfo
./sources/cxx-stl/system/include/typeinfo
./sources/cxx-stl/gabi++/include/typeinfo
./sources/cxx-stl/stlport/stlport/typeinfo
kerwin@ubuntu:~/cerbero/android-ndk-r10d$

**Comment by nirbheek** [comment]
So, I got this error once, but I rebuilt ICU and it went away. I think there's a race condition somewhere inside ICU's build system.

**Comment by KerwinMa** [comment]
Yes, you're right. I rebuilt ICU as well and it won't happen again. Thanks.

**Comment by nirbheek** [comment]
Please leave this bug open; I want to trace this and fix it properly.

**Comment by nirbheek** [comment]
Moved to https://github.com/EricssonResearch/cerbero/issues/1
