### ISSUE TITLE
fatal error: gir/GIRepository-2.0.gir.h: No such file or directory

### ISSUE THREAD

**Issue by KerwinMa** [nirbheek/cerbero#18]
I am stopped with last step and trying to figure out the reason now. Please advise if you had the same issue before.

**Comment by nirbheek** [comment]
I need more details; what gives this error? What's the log file for the build?

**Comment by KerwinMa** [comment]
Sorry, the logs details are:[(36/36) openwebrtc -> fetch ]
-----> Step done
[(36/36) openwebrtc -> extract ]
-----> Step done
[(36/36) openwebrtc -> configure ]
-----> Step done
[(36/36) openwebrtc -> compile ]
make[1]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1'
make[2]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/transport'
make[2]: `.gitignore' is up to date.
make[2]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/transport'
make[2]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/local'
make[2]: `.gitignore' is up to date.
make[2]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/local'
make[2]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/owr'
make[2]: `.gitignore' is up to date.
make[2]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/owr'
make[2]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge'
make[2]: `.gitignore' is up to date.
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/client'
make[3]: `.gitignore' is up to date.
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/client'
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/seed'
make[3]: `.gitignore' is up to date.
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/seed'
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/shared'
make[3]: `.gitignore' is up to date.
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/shared'
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/worker'
make[3]: `.gitignore' is up to date.
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/worker'
make[2]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge'
make[2]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/docs'
make[2]: `.gitignore' is up to date.
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/docs/reference'
make[3]: `.gitignore' is up to date.
make[4]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/docs/reference/owr'
make[4]: `.gitignore' is up to date.
make[4]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/docs/reference/owr'
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/docs/reference'
make[2]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/docs'
make[2]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bindings'
make[2]: `.gitignore' is up to date.
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bindings/java'
make[3]: `.gitignore' is up to date.
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bindings/java'
make[2]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bindings'
make[2]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/tests'
make[2]: `.gitignore' is up to date.
make[2]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/tests'
make[1]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1'
make  all-recursive
make[1]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1'
Making all in transport
make[2]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/transport'
make[2]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/transport'
Making all in local
make[2]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/local'
make[2]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/local'
Making all in owr
make[2]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/owr'
make  all-am
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/owr'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/owr'
make[2]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/owr'
Making all in bridge
make[2]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge'
Making all in client
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/client'
make  all-am
make[4]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/client'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/client'
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/client'
Making all in seed
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/seed'
make  all-am
make[4]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/seed'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/seed'
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/seed'
Making all in shared
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/shared'
make  all-am
make[4]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/shared'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/shared'
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/shared'
Making all in worker
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/worker'
make  all-am
make[4]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/worker'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/worker'
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge/worker'
make[3]: Entering directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge'
/bin/bash ../libtool  --tag=CC   --mode=compile arm-linux-androideabi-gcc -fuse-ld=gold -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -DPACKAGE_LOCALE_DIR=\""/home/kerwin/cerbero/dist/android_armv7/share/locale"\" -DPACKAGE_SRC_DIR=\""."\" -DPACKAGE_DATA_DIR=\""/home/kerwin/cerbero/dist/android_armv7/share/openwebrtc"\" -pthread -I/home/kerwin/cerbero/dist/android_armv7/include/glib-2.0 -I/home/kerwin/cerbero/dist/android_armv7/lib/glib-2.0/include  -pthread -I/home/kerwin/cerbero/dist/android_armv7/include/seed-gtk3 -I/home/kerwin/cerbero/dist/android_armv7/include/webkitgtk-3.0 -I/home/kerwin/cerbero/dist/android_armv7/include/gobject-introspection-1.0 -I/home/kerwin/cerbero/dist/android_armv7/lib/libffi-3.2.1/include -I/home/kerwin/cerbero/dist/android_armv7/include/glib-2.0 -I/home/kerwin/cerbero/dist/android_armv7/lib/glib-2.0/include  -I../owr -I../owr -I../bridge --sysroot=/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm -I/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm/usr/include -DANDROID -DPIC -D__ARM_ARCH_7A__  -Wall -Wextra -Werror "-g" -ansi -Wall -g -Os --sysroot=/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm -I/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm/usr/include -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -fPIC -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64  -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -DANDROID -DPIC -D__ARM_ARCH_7A__  -Wa,--noexecstack -MT libopenwebrtc_bridge_la-owr_bridge.lo -MD -MP -MF .deps/libopenwebrtc_bridge_la-owr_bridge.Tpo -c -o libopenwebrtc_bridge_la-owr_bridge.lo `test -f 'owr_bridge.c' || echo './'`owr_bridge.c
libtool: compile:  arm-linux-androideabi-gcc -fuse-ld=gold -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -DPACKAGE_LOCALE_DIR=\"/home/kerwin/cerbero/dist/android_armv7/share/locale\" -DPACKAGE_SRC_DIR=\".\" -DPACKAGE_DATA_DIR=\"/home/kerwin/cerbero/dist/android_armv7/share/openwebrtc\" -pthread -I/home/kerwin/cerbero/dist/android_armv7/include/glib-2.0 -I/home/kerwin/cerbero/dist/android_armv7/lib/glib-2.0/include -pthread -I/home/kerwin/cerbero/dist/android_armv7/include/seed-gtk3 -I/home/kerwin/cerbero/dist/android_armv7/include/webkitgtk-3.0 -I/home/kerwin/cerbero/dist/android_armv7/include/gobject-introspection-1.0 -I/home/kerwin/cerbero/dist/android_armv7/lib/libffi-3.2.1/include -I/home/kerwin/cerbero/dist/android_armv7/include/glib-2.0 -I/home/kerwin/cerbero/dist/android_armv7/lib/glib-2.0/include -I../owr -I../owr -I../bridge --sysroot=/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm -I/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm/usr/include -DANDROID -DPIC -D__ARM_ARCH_7A__ -Wall -Wextra -Werror -g -ansi -Wall -g -Os --sysroot=/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm -I/home/kerwin/cerbero/android-ndk-r10d/platforms/android-9/arch-arm/usr/include -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -fPIC -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -DANDROID -DPIC -D__ARM_ARCH_7A__ -Wa,--noexecstack -MT libopenwebrtc_bridge_la-owr_bridge.lo -MD -MP -MF .deps/libopenwebrtc_bridge_la-owr_bridge.Tpo -c owr_bridge.c  -fPIC -DPIC -o .libs/libopenwebrtc_bridge_la-owr_bridge.o
owr_bridge.c:48:38: fatal error: gir/GIRepository-2.0.gir.h: No such file or directory
 #include <gir/GIRepository-2.0.gir.h>
                                      ^
compilation terminated.
make[3]: *** [libopenwebrtc_bridge_la-owr_bridge.lo] Error 1
make[3]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1/bridge'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/kerwin/cerbero/sources/android_armv7/openwebrtc-0.1'
make: *** [all] Error 2
Running command 'make'

***** Error running 'package' command:
Recipe 'openwebrtc' failed at the build step 'compile'

kerwin@ubuntu:~/cerbero$ find ./ -name "GIRepository-2.0.gir.h"
kerwin@ubuntu:~/cerbero$ find ./ -name "GIRepos"
kerwin@ubuntu:~/cerbero$ find ./ -name "gir"
./sources/linux_x86_64/gobject-introspection-1.42.0/gir
./sources/android_armv7/gobject-introspection-1.40.0/gir
./dist/android_armv7/include/gobject-introspection-1.0/gir
kerwin@ubuntu:~/cerbero$ find ./ -name "gobject-introspection-1.0"
./dist/linux_x86_64/include/gobject-introspection-1.0
./dist/linux_x86_64/share/gobject-introspection-1.0
./dist/android_armv7/include/gobject-introspection-1.0
./dist/android_armv7/share/gobject-introspection-1.0

**Comment by KerwinMa** [comment]
There is a 'gir' folder located in ./dist/android_armv7/include/gobject-introspection-1.0 folder, but no 'GIRepository-2.0.gir.h' file.

**Comment by KerwinMa** [comment]
GIRepository-2.0.gir.h
GLib-2.0.gir.h
GModule-2.0.gir.h
GObject-2.0.gir.h
Gio-2.0.gir.h

I copied these files into the empty folder and got another error:
(36/36) openwebrtc -> fetch ]
-----> Step done
[(36/36) openwebrtc -> extract ]
-----> Step done
[(36/36) openwebrtc -> configure ]
-----> Step done
[(36/36) openwebrtc -> compile ]
[(36/36) openwebrtc -> install ]
[(36/36) openwebrtc -> post_install ]
Recipe 'openwebrtc' failed at the build step 'post_install'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "/home/kerwin/cerbero/recipes/openwebrtc.recipe", line 210, in post_install
    f.write(self.owr_version_id)
AttributeError: 'Recipe' object has no attribute 'owr_version_id'
Select an action to proceed:

**Comment by KerwinMa** [comment]
Here is more information what I did:
I cloned http://cgit.freedesktop.org/gstreamer/cerbero 1st (with fix #14), and found it won't git openwebRTC source. Then I copied over yours (https://github.com/nirbheek/cerbero) and overwrote the files.

**Comment by nirbheek** [comment]
Uhm, that seems fishy. Could you do a new git checkout of nirbheek/cerbero, and try again? It seems like something is quite broken. What you did there is not how you use git repositories. :smile:

**Comment by nirbheek** [comment]
All development has moved to https://github.com/EricssonResearch/cerbero
